/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	SetTopWindow( new MainFrame( NULL ) );
	GetTopWindow()->Show();
	
	// true = enter the main loop
	return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation 
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow *parent) : MainFrameBase( parent )
{
}

MainFrame::~MainFrame()
{
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
	Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
	Destroy();
}
        void MainFrame::tombol_baca( wxCommandEvent& event ){
            //ambil lokasi dari file dengan file picker
            wxString lokasi_file_wx = m_filePicker1->GetPath();
            //konversi dengan wxstring ke string
            std::string lokasi_file = lokasi_file_wx.ToStdString();
            
            std::ifstream fileku(lokasi_file);
            std::string baris;
            
            if (fileku.is_open())
            {
                while(getline(fileku,baris))
                {
                    m_textCtrl1->WriteText(baris);
                    m_textCtrl1->WriteText("\n");
                }
                fileku.close();
            }
            else{
                std::cout<<"file tidak dapat dibuka";
            }
        }
		void MainFrame::tombol_tulis( wxCommandEvent& event ){
            wxString lokasi_file_wx = m_filePicker1->GetPath();
            std::string lokasi_file = lokasi_file_wx.ToStdString();
            
            wxString ambil_teks = m_textCtrl1->GetValue();
            std::string s_ambil_teks = ambil_teks.ToStdString();
            
            std::ofstream fileku(lokasi_file);
            if (fileku.is_open())
            {
                fileku<<s_ambil_teks;
                fileku.close();
            }
            else
            {
                std::cout <<"file tidak dapat dibuka";
            }
        }
		void MainFrame::tombol_bacatulis( wxCommandEvent& event ){
            
        }